version: "3.8"
services:
   client:
      build:
         context: ./client # Emplacement du dossier
         dockerfile: Dockerfile # Nom du fichier
         target: prod # Nom du stage utilisé
      container_name: client
      restart: always
      # volumes: 
      # - ./:/usr/src/app
      ports:
         - 3000:3000 

